Upload the two datasets

In [275]:
# import dataset e visualizzazione
import pandas as pd 
import numpy as np 
import re

df= pd.read_csv('C:/Users/luca/Desktop/Python Dataset/googleplaystore.csv')
df1 = pd.read_csv("C:/Users/luca/Desktop/Python Dataset/googleplaystore_user_reviews.csv")
df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

In [276]:
df1.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [277]:
df.dropna(subset=["Android Ver"], inplace = True) #delete Nan from Android Ver
df["Android Ver"]

0              4.0.3 and up
1              4.0.3 and up
2              4.0.3 and up
3                4.2 and up
4                4.4 and up
5                2.3 and up
6              4.0.3 and up
7                4.2 and up
8                3.0 and up
9              4.0.3 and up
10               4.1 and up
11               4.0 and up
12               4.1 and up
13               4.4 and up
14               2.3 and up
15               4.2 and up
16               4.1 and up
17               2.3 and up
18             4.0.3 and up
19               4.1 and up
20               4.1 and up
21             4.0.3 and up
22             4.0.3 and up
23               4.1 and up
24               4.1 and up
25               3.0 and up
26             4.0.3 and up
27             4.0.3 and up
28               2.3 and up
29               2.3 and up
                ...
10811           4.4W and up
10812          4.0.3 and up
10813            4.1 and up
10814            3.0 and up
10815            4.2 and up
10816            4.1 and up
10817            5.0 and up
10818            2.2 and up
10819            4.1 and up
10820            4.1 and up
10821          4.0.3 and up
10822            4.4 and up
10823          4.0.3 and up
10824            4.4 and up
10825            4.0 and up
10826    Varies with device
10827          4.0.3 and up
10828            4.0 and up
10829            4.1 and up
10830            1.6 and up
10831            4.0 and up
10832            2.1 and up
10833            2.2 and up
10834            4.1 and up
10835            4.0 and up
10836            4.1 and up
10837            4.1 and up
10838            2.2 and up
10839    Varies with device
10840    Varies with device
Name: Android Ver, Length: 10838, dtype: object

3) Trasformo 'Varies with device in NaN' in tutto il dataframe.

Svolgo subito il punto 3 perché da qui dipende anche il punto 1

In [278]:
# 3. Trasformo 'Varies with device in NaN' in tutto il dataframe.

df[df=='Varies with device']=np.nan

C:\Users\luca\AnacondaPy\lib\site-packages\pandas\core\ops.py:1649: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

In [279]:
df[df == "Varies with device"].count() #Verifico se "Varies with device" c'è ancora

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    0
Genres            0
Last Updated      0
Current Ver       0
Android Ver       0
dtype: int64

Convert the app sizes to a number

In [280]:
# 1.Converti le dimensioni delle app in un numero
df['Size'].str.extractall(r'([a-z])', flags = re.IGNORECASE).count() #Conto i valori che contengono lettere.

0    9143
dtype: int64

In [281]:
df['Size'].str.extractall(r'([kM]$)').count() 
#Le due righe combaciano perfettamente quindi ho verificato che tutti i valori finiscono per M o per k

0    9143
dtype: int64

In [282]:
Kilo= df['Size'].str.extractall(r'(k$)').index.get_level_values(0) #metto a 0 perchè è un MultiIndex.
# è un oggetto Index contenente tutti gli Indici

In [283]:
df['Size'].replace(regex=True, inplace=True, to_replace=r'\D$', value=r'') #elimino le righe con i valori M e k

In [284]:
df['Size'].str.extractall(r'([a-z])', flags = re.IGNORECASE) #verifico che in tutte le righe non vi siano più lettere

Empty DataFrame
Columns: [0]
Index: []

In [285]:
df['Size']=pd.to_numeric(df['Size']) # convertire tutti i valori in float per avere la stessa scala rispetto a MB

In [286]:
df["Size"].loc[Kilo] = (df["Size"].loc[Kilo]/1000) # conversione da kb a mb e divisione per mille
df.rename(columns={'Size': 'Size(MB)'}, inplace=True) #ora che i valori sono in megabyte, rinomino la colonna
df.head() # Visualizzazione testa

C:\Users\luca\AnacondaPy\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

,App,Category,Rating,Reviews,Size(MB),Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19.0,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25.0,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",NaN,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up

Convert the number of installs to a number

In [287]:
# 2.Convertire il numero di installazioni in un numero

df["Installs"].replace("\+|,", value = "", regex = True, inplace = True) # Sostituzione del simbolo "+"

df["Installs"] = pd.to_numeric(df["Installs"]) # Conversione numerica

df['Installs'].head(20) # verificare l'output

0        10000
1       500000
2      5000000
3     50000000
4       100000
5        50000
6        50000
7      1000000
8      1000000
9        10000
10     1000000
11     1000000
12    10000000
13      100000
14      100000
15        5000
16      500000
17       10000
18     5000000
19    10000000
Name: Installs, dtype: int64

Convert Current Ver and Android Ver into a dotted number (e.g. 4.0.3 or 4.2)

In [288]:
# 4 Converti Current Ver e Android Ver in un numero punteggiato (ad esempio 4.0.3 o 4.2) 
df["Current Ver"].head(20)

0        1.0.0
1        2.0.0
2        1.2.4
3          NaN
4          1.1
5          1.0
6          1.1
7     6.1.61.1
8        2.9.2
9          2.8
10       1.0.4
11      1.0.15
12         3.8
13       1.0.4
14       1.2.3
15         NaN
16         3.1
17         1.0
18       2.2.5
19       5.5.4
Name: Current Ver, dtype: object

In [289]:
df["Android Ver"].replace("[a-z]+|[A-z]+", value = "" ,regex = True, inplace = True) #cancello le lettere in modo tale da lasciare solo la parte numerica
df["Current Ver"].replace("[a-z]+|[A-z]+", value = "", regex = True, inplace = True) #cancello le lettere in modo tale da lasciare solo la parte numerica

In [290]:
df["Android Ver"] #controllare

0        4.0.3
1        4.0.3
2        4.0.3
3          4.2
4          4.4
5          2.3
6        4.0.3
7          4.2
8          3.0
9        4.0.3
10         4.1
11         4.0
12         4.1
13         4.4
14         2.3
15         4.2
16         4.1
17         2.3
18       4.0.3
19         4.1
20         4.1
21       4.0.3
22       4.0.3
23         4.1
24         4.1
25         3.0
26       4.0.3
27       4.0.3
28         2.3
29         2.3
          ...
10811      4.4
10812    4.0.3
10813      4.1
10814      3.0
10815      4.2
10816      4.1
10817      5.0
10818      2.2
10819      4.1
10820      4.1
10821    4.0.3
10822      4.4
10823    4.0.3
10824      4.4
10825      4.0
10826        NaN
10827    4.0.3
10828      4.0
10829      4.1
10830      1.6
10831      4.0
10832      2.1
10833      2.2
10834      4.1
10835      4.0
10836      4.1
10837      4.1
10838      2.2
10839        NaN
10840        NaN
Name: Android Ver, Length: 10838, dtype: object

In [291]:
df["Current Ver"] #controllare

0             1.0.0
1             2.0.0
2             1.2.4
3               NaN
4               1.1
5               1.0
6               1.1
7          6.1.61.1
8             2.9.2
9               2.8
10            1.0.4
11           1.0.15
12              3.8
13            1.0.4
14            1.2.3
15              NaN
16              3.1
17              1.0
18            2.2.5
19            5.5.4
20              4.0
21              1.1
22          2.2.6.2
23            1.0.0
24            1.1.3
25              1.5
26            1.0.8
27             1.03
28              6.0
29              1.0
            ...
10811         1.3.6
10812        2.0.20
10813        2.1.10
10814         1.3.1
10815       7.0.4.6
10816         2.1.8
10817    1.0.612928
10818           2.3
10819         0.3.4
10820         3.8.0
10821           1.0
10822             1
10823           1.0
10824         2.2.2
10825           1.0
10826           NaN
10827        2.0.20
10828         2.0.1
10829          2.96
10830           1.5
10831     2.0.148.0
10832           6.0
10833           0.8
10834         1.0.0
10835         1.1.5
10836          1.48
10837           1.0
10838           1.0
10839           NaN
10840           NaN
Name: Current Ver, Length: 10838, dtype: object

In [292]:
df.loc[100] #Verifichiamo una riga a caso

App               Natural recipes for your beauty
Category                                   BEAUTY
Rating                                        4.7
Reviews                                      1150
Size(MB)                                      9.8
Installs                                   100000
Type                                         Free
Price                                           0
Content Rating                           Everyone
Genres                                     Beauty
Last Updated                         May 15, 2018
Current Ver                                   4.0
Android Ver                                 4.1
Name: 100, dtype: object

Remove the duplicates

In [293]:
# 5.Rimuovi i duplicati
df.drop_duplicates(inplace=True) #elimino le righe che sono esattamente uguali. Ci sono ancora app uguali che hanno molto probabilmente rewiew diverse.
# Prendo quelle con i dati più recenti

In [294]:
df.duplicated(subset='App').value_counts()

False    9657
True      698
dtype: int64

In [295]:
df[df["App"] == "Coloring book moana"] #controlla gli indici di questa app

,App,Category,Rating,Reviews,Size(MB),Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3
2033,Coloring book moana,FAMILY,3.9,974,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3

In [296]:
df.sort_values(by=['Reviews'], ascending = False, inplace= True) #ordino il dataframe dalle app che hanno più Reviews a quelle che hanno meno Reviews

df.drop_duplicates(subset=['App'], inplace=True) 

df[df['App']=='Coloring book moana'] #controlla gli indici di questa app

,App,Category,Rating,Reviews,Size(MB),Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
2033,Coloring book moana,FAMILY,3.9,974,14.0,500000,Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3

In [297]:
df.duplicated(subset='App').value_counts()

False    9657
dtype: int64

For each category, compute the number of apps

In [298]:
df.groupby("Category", as_index = False)[["App"]].count()

               Category   App
0        ART_AND_DESIGN    61
1     AUTO_AND_VEHICLES    85
2                BEAUTY    53
3   BOOKS_AND_REFERENCE   222
4              BUSINESS   420
5                COMICS    56
6         COMMUNICATION   315
7                DATING   171
8             EDUCATION   108
9         ENTERTAINMENT    87
10               EVENTS    64
11               FAMILY  1877
12              FINANCE   345
13       FOOD_AND_DRINK   112
14                 GAME   942
15   HEALTH_AND_FITNESS   288
16       HOUSE_AND_HOME    73
17   LIBRARIES_AND_DEMO    84
18            LIFESTYLE   369
19  MAPS_AND_NAVIGATION   131
20              MEDICAL   395
21   NEWS_AND_MAGAZINES   254
22            PARENTING    60
23      PERSONALIZATION   374
24          PHOTOGRAPHY   281
25         PRODUCTIVITY   374
26             SHOPPING   202
27               SOCIAL   239
28               SPORTS   325
29                TOOLS   828
30     TRAVEL_AND_LOCAL   219
31        VIDEO_PLAYERS   164
32              WEATHER    79

For each category, compute the average rating

In [299]:
# 7. Per ogni categoria, calcola la valutazione media 
df.groupby("Category", as_index = False)["Rating"].mean()

               Category    Rating
0        ART_AND_DESIGN  4.359322
1     AUTO_AND_VEHICLES  4.190411
2                BEAUTY  4.278571
3   BOOKS_AND_REFERENCE  4.344970
4              BUSINESS  4.098479
5                COMICS  4.181481
6         COMMUNICATION  4.121484
7                DATING  3.970149
8             EDUCATION  4.358879
9         ENTERTAINMENT  4.129885
10               EVENTS  4.435556
11               FAMILY  4.183656
12              FINANCE  4.115563
13       FOOD_AND_DRINK  4.171277
14                 GAME  4.243352
15   HEALTH_AND_FITNESS  4.243033
16       HOUSE_AND_HOME  4.140984
17   LIBRARIES_AND_DEMO  4.178125
18            LIFESTYLE  4.093355
19  MAPS_AND_NAVIGATION  4.036441
20              MEDICAL  4.166552
21   NEWS_AND_MAGAZINES  4.121569
22            PARENTING  4.300000
23      PERSONALIZATION  4.331419
24          PHOTOGRAPHY  4.157414
25         PRODUCTIVITY  4.183389
26             SHOPPING  4.230556
27               SOCIAL  4.247291
28               SPORTS  4.216154
29                TOOLS  4.039917
30     TRAVEL_AND_LOCAL  4.069519
31        VIDEO_PLAYERS  4.044966
32              WEATHER  4.243056

Create two dataframes: one for the genres and one bridging apps and genres. So that, for instance, the app Pixel Draw - Number Art Coloring Book appears twice in the bridging table, once for Art & Design, once for Creativity

In [300]:
# 8.Crea due dataframe: uno per i generi e un app e generi per il bridging. 
#Così, ad esempio, l'app Pixel Draw - Number Art Coloring Book appare due volte nella tabella di bridging, 
#una volta per Art & Design, una volta per Creativity 

df[df['App']=='Pixel Draw - Number Art Coloring Book']

,App,Category,Rating,Reviews,Size(MB),Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8,100000,Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4

In [301]:
app_gene = df[['App', 'Genres']] #Creo un dataframe con solo le due colonne che mi interessano

app_gene.head(20) #mostra il nuovo dataframe

,App,Genres
2989,GollerCepte Live Score,Sports
4970,Ad Block REMOVER - NEED ROOT,Tools
2705,SnipSnap Coupon App,Shopping
3049,US Open Tennis Championships 2018,Sports
3229,DreamTrips,Travel & Local
7002,Adult Color by Number Book - Paint Mandala Pages,Entertainment
6724,BSPlayer ARMv7 VFP CPU support,Video Players & Editors
7982,"Easy Resume Builder, Resume help, Curriculum v...",Tools
353,MegaFon Dashboard,Communication
326,Buff Thun - Daily Free Webtoon / Comics / Web ...,Comics
5326,Al jazeera TV,Entertainment
3874,Rope Hero Return of a Legend,Arcade
10383,Family Guy The Quest for Stuff,Adventure
7351,tutti.ch - Free Classifieds,Shopping
2349,Teach Me Anatomy,Medical
996,Funny Pics,Entertainment
78,Best Car Wallpapers,Auto & Vehicles
9112,Files To SD Card Pro,Tools
4183,HSPA+ Tweaker (3G booster),Tools
6996,Art Pixel Coloring. Color by Number.,Entertainment

In [302]:
genres =app_gene["Genres"].str.split(";", expand = True) #creo un dataframe con due Colonne. Una per ogni genere

genres

                             0     1
2989                    Sports  None
4970                     Tools  None
2705                  Shopping  None
3049                    Sports  None
3229            Travel & Local  None
7002             Entertainment  None
6724   Video Players & Editors  None
7982                     Tools  None
353              Communication  None
326                     Comics  None
5326             Entertainment  None
3874                    Arcade  None
10383                Adventure  None
7351                  Shopping  None
2349                   Medical  None
996              Entertainment  None
78             Auto & Vehicles  None
9112                     Tools  None
4183                     Tools  None
6996             Entertainment  None
4957              Productivity  None
1982                    Action  None
741                  Education  None
3057                    Sports  None
1021                    Events  None
3595                 Parenting  None
7826                 Education  None
8936                     Tools  None
4840                  Strategy  None
7443                    Action  None
...                        ...   ...
6653                 Lifestyle  None
478                     Dating  None
2433                   Medical  None
9421                     Tools  None
2434                   Medical  None
10417                  Finance  None
8828          Health & Fitness  None
2435                   Medical  None
2436                   Medical  None
9414                 Education  None
479                     Dating  None
8871              Art & Design  None
7386                  Business  None
8870                  Business  None
7202                 Education  None
5231         Maps & Navigation  None
4273              Productivity  None
5688                 Lifestyle  None
6176          News & Magazines  None
5494                  Strategy  None
6644                  Business  None
5234          News & Magazines  None
2422                   Medical  None
8851                 Lifestyle  None
7384          Health & Fitness  None
5232             Communication  None
7382                   Finance  None
2424                   Medical  None
10399                  Medical  None
5113                  Business  None

[9657 rows x 2 columns]

In [303]:
app_gene['Genre'] = genres[0] #sostituisco la colonna 'Genre' (che aveva le coppie di generi) con la colonna del primo genere per ogni app

app_gene['Genre']

C:\Users\luca\AnacondaPy\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

2989                      Sports
4970                       Tools
2705                    Shopping
3049                      Sports
3229              Travel & Local
7002               Entertainment
6724     Video Players & Editors
7982                       Tools
353                Communication
326                       Comics
5326               Entertainment
3874                      Arcade
10383                  Adventure
7351                    Shopping
2349                     Medical
996                Entertainment
78               Auto & Vehicles
9112                       Tools
4183                       Tools
6996               Entertainment
4957                Productivity
1982                      Action
741                    Education
3057                      Sports
1021                      Events
3595                   Parenting
7826                   Education
8936                       Tools
4840                    Strategy
7443                      Action
                  ...
6653                   Lifestyle
478                       Dating
2433                     Medical
9421                       Tools
2434                     Medical
10417                    Finance
8828            Health & Fitness
2435                     Medical
2436                     Medical
9414                   Education
479                       Dating
8871                Art & Design
7386                    Business
8870                    Business
7202                   Education
5231           Maps & Navigation
4273                Productivity
5688                   Lifestyle
6176            News & Magazines
5494                    Strategy
6644                    Business
5234            News & Magazines
2422                     Medical
8851                   Lifestyle
7384            Health & Fitness
5232               Communication
7382                     Finance
2424                     Medical
10399                    Medical
5113                    Business
Name: Genre, Length: 9657, dtype: object

In [304]:
secondgenre = pd.DataFrame({'App': app_gene['App'],'Genre':genres[1]}) #creo un dataframe che ha le app in corrispondenza del loro secondo genere. Le app che non hanno il secondo genere hanno un missing value

secondgenre

                                                     App Genre
2989                              GollerCepte Live Score  None
4970                        Ad Block REMOVER - NEED ROOT  None
2705                                 SnipSnap Coupon App  None
3049                   US Open Tennis Championships 2018  None
3229                                          DreamTrips  None
7002    Adult Color by Number Book - Paint Mandala Pages  None
6724                      BSPlayer ARMv7 VFP CPU support  None
7982   Easy Resume Builder, Resume help, Curriculum v...  None
353                                    MegaFon Dashboard  None
326    Buff Thun - Daily Free Webtoon / Comics / Web ...  None
5326                                       Al jazeera TV  None
3874                        Rope Hero Return of a Legend  None
10383                     Family Guy The Quest for Stuff  None
7351                         tutti.ch - Free Classifieds  None
2349                                    Teach Me Anatomy  None
996                                           Funny Pics  None
78                                   Best Car Wallpapers  None
9112                                Files To SD Card Pro  None
4183                          HSPA+ Tweaker (3G booster)  None
6996                Art Pixel Coloring. Color by Number.  None
4957                                        Adblock Fast  None
1982                                     Zombie Catchers  None
741                               Udemy - Online Courses  None
3057                      Tennis 24 - tennis live scores  None
1021     PTI Flex Maker, Photo Frame Editor & Songs 2018  None
3595                                    Kids Craft Ideas  None
7826                                   CS Interview FAQs  None
8936                                            AKASO DV  None
4840                               Z-Empire: Dead Strike  None
7443                            Gang Wars of San Andreas  None
...                                                  ...   ...
6653                               Bar BQ Tonight Dublin  None
478                                    Truth or Dare Pro  None
2433                                          RT 516 VET  None
9421                                          Verdant EI  None
2434                                EXOGEN Connects (US)  None
10417                                          FH Wallet  None
8828                                        DS Companion  None
2435           Full Code - Emergency Medicine Simulation  None
2436                                         Maricopa AH  None
9414                                            Yeled EI  None
479      Private Dating, Hide App- Blue for PrivacyHider  None
8871                              Test Application DT 02  None
7386                                      RGN CI-Control  None
8870                                              PAY DT  None
7202                                     ABAI CE Scanner  None
5231                                        AJ Reminders  None
4273                                J. Polep Plus Mobile  None
5688                             Au Rubis les bijoutiers  None
6176                                             Dete.bg  None
5494                                   AQ: First Contact  None
6644                       Bill Miller Bar-B-Q Store Ops  None
5234                                        Aj. Vallbona  None
2422                                           Visualmed  None
8851                                                  DT  None
7384                      All-night drugstore CI & Price  None
5232                           tournaments and more.aj.2  None
7382                           1st Fed CI Mobile Banking  None
2424                                           OrthoFlow  None
10399                     Familial Hypercholesterolaemia  None
5113                                    Ag-Pro Companies  None

[9657 rows x 2 columns]

In [305]:
app_gene.drop(columns = ["Genres"], inplace = True) #elimino la colonna genres di partenza dal app_gene

C:\Users\luca\AnacondaPy\lib\site-packages\pandas\core\frame.py:3940: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [306]:
secondgenre.dropna(subset = ['Genre'], inplace=True) #elimino i missing values per le app che non hanno il secondo genere

In [307]:
dfconcat=pd.concat([app_gene, secondgenre], ignore_index=True) #creo il dataframe finale che ha tutte le app in corrispondenza di un genere. Le app che hanno due generi compaiono due volte. Aggiungo ignore_index=True, sennò in corrispondenza dell'istanza 4 ci sarebbero state due Pixel Draw, una per ogni genere. Invece ora la prima è sulla riga 4, la seconda è sulla riga 10839

In [308]:
dfconcat[dfconcat['App']=='Pixel Draw - Number Art Coloring Book']

                                        App         Genre
90    Pixel Draw - Number Art Coloring Book  Art & Design
9663  Pixel Draw - Number Art Coloring Book    Creativity

For each genre, create a new column of the original dataframe. The new columns must have boolean values (True if the app has a given genre)

In [309]:
# 9.Per ogni genere, crea una nuova colonna del dataframe originale. 
#Le nuove colonne devono avere valori booleani (Vero se l'app ha un determinato genere) 

df=df.join(genres) #aggiungo al dataframe le due colonne genere1 e genere 2 che avevo creato.

In [310]:
df.rename(columns={0: 'Genre1', 1: 'Genre2'}, inplace=True)

In [311]:
df = pd.concat([df, pd.get_dummies(df['Genre1']).astype(bool), pd.get_dummies(df['Genre2']).astype(bool)], axis=1) #creo le colonne binarie per il primo genere e per il secondo genere.

In [312]:
df[['App','Art & Design', 'Creativity']].loc[4]

App             Pixel Draw - Number Art Coloring Book
Art & Design                                     True
Creativity                                       True
Name: 4, dtype: object

For each genre, compute the average rating. What is the genre with highest average?

In [313]:
# 10.Per ogni genere, calcola la valutazione media. Qual è il genere con la media più alta? 
dfgenere = df.merge(dfconcat, on='App') #creo un nuovo datframe che ha che ha la stessa app che compare due volte (solo per le app con due generi), una volta per genere.
dfgenere.head()

,App,Category,Rating,Reviews,Size(MB),Installs,Type,Price,Content Rating,Genres,...,Video Players & Editors,Weather,Word,Action & Adventure,Brain Games,Creativity,Education,Music & Video,Pretend Play,Genre
0,GollerCepte Live Score,SPORTS,4.2,9992,31.000,1000000,Free,0,Everyone,Sports,...,False,False,False,False,False,False,False,False,False,Sports
1,Ad Block REMOVER - NEED ROOT,TOOLS,3.3,999,0.091,100000,Free,0,Everyone,Tools,...,False,False,False,False,False,False,False,False,False,Tools
2,SnipSnap Coupon App,SHOPPING,4.2,9975,18.000,1000000,Free,0,Everyone,Shopping,...,False,False,False,False,False,False,False,False,False,Shopping
3,US Open Tennis Championships 2018,SPORTS,4.0,9971,33.000,1000000,Free,0,Everyone,Sports,...,False,False,False,False,False,False,False,False,False,Sports
4,DreamTrips,TRAVEL_AND_LOCAL,4.7,9971,22.000,500000,Free,0,Teen,Travel & Local,...,False,False,False,False,False,False,False,False,False,Travel & Local

In [314]:
dfgenere.groupby('Genre')['Rating'].mean()

Genre
Action                     4.247697
Action & Adventure         4.288542
Adventure                  4.191026
Arcade                     4.277838
Art & Design               4.350000
Auto & Vehicles            4.190411
Beauty                     4.278571
Board                      4.287719
Books & Reference          4.343275
Brain Games                4.358462
Business                   4.098479
Card                       4.076087
Casino                     4.286486
Casual                     4.139352
Comics                     4.181481
Communication              4.121790
Creativity                 4.306250
Dating                     3.970149
Education                  4.290630
Educational                4.100000
Entertainment              4.093028
Events                     4.435556
Finance                    4.115563
Food & Drink               4.171277
Health & Fitness           4.243496
House & Home               4.140984
Libraries & Demo           4.178125
Lifestyle                  4.094040
Maps & Navigation          4.036441
Medical                    4.166552
Music                      4.219048
Music & Audio              4.300000
Music & Video              4.229032
News & Magazines           4.121569
Parenting                  4.300000
Personalization            4.331419
Photography                4.157414
Pretend Play               4.238235
Productivity               4.183389
Puzzle                     4.370968
Racing                     4.174757
Role Playing               4.272072
Shopping                   4.230556
Simulation                 4.154500
Social                     4.247291
Sports                     4.225185
Strategy                   4.227368
Tools                      4.039917
Travel & Local             4.069519
Trivia                     4.039286
Video Players & Editors    4.044667
Weather                    4.243056
Word                       4.318182
Name: Rating, dtype: float64

In [315]:
print("The average of the highest rating corresponds to the genres is " +dfgenere.groupby('Genre')['Rating'].mean().argmax() + " ,with a value of " + str(dfgenere.groupby('Genre')['Rating'].mean().max()))

The average of the highest rating corresponds to the genres is Events ,with a value of 4.435555555555555

C:\Users\luca\AnacondaPy\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
The current behaviour of 'Series.argmax' is deprecated, use 'idxmax'
instead.
The behavior of 'argmax' will be corrected to return the positional
maximum in the future. For now, use 'series.values.argmax' or
'np.argmax(np.array(values))' to get the position of the maximum
row.
  """Entry point for launching an IPython kernel.

For each app, compute the approximate income, obtain as a product of number of installs and price.

In [316]:
11# Per ogni app, calcola il reddito approssimativo, ottieni come prodotto del numero di installazioni e del prezzo.
df['Installs'].value_counts()

1000000       1418
100000        1113
10000         1029
10000000       934
1000           887
100            710
5000000        608
500000         505
50000          469
5000           468
10             385
500            328
50             204
50000000       203
100000000      188
5               82
1               67
500000000       24
1000000000      20
0               15
Name: Installs, dtype: int64

In [317]:
df['Price'].value_counts()

0          8902
$0.99       145
$2.99       124
$1.99        73
$4.99        70
$3.99        57
$1.49        45
$5.99        26
$2.49        25
$9.99        19
$399.99      12
$6.99        11
$4.49         9
$14.99        9
$7.99         7
$3.49         7
$8.99         5
$6.49         5
$5.49         5
$29.99        5
$19.99        5
$12.99        4
$24.99        3
$1.00         3
$2.00         3
$11.99        3
$7.49         2
$1.70         2
$39.99        2
$13.99        2
           ...
$74.99        1
$2.60         1
$3.90         1
$394.99       1
$3.04         1
$4.59         1
$5.00         1
$1.59         1
$4.60         1
$18.99        1
$33.99        1
$30.99        1
$3.95         1
$2.50         1
$46.99        1
$4.29         1
$389.99       1
$1.20         1
$37.99        1
$14.00        1
$9.00         1
$400.00       1
$379.99       1
$4.85         1
$3.08         1
$1.61         1
$2.95         1
$1.26         1
$200.00       1
$299.99       1
Name: Price, Length: 92, dtype: int64

In [318]:
df['Price']=df['Price'].replace(r"\$", value = "", regex = True) #faccio questa operazione per togliere il $
df["Price"] = pd.to_numeric(df["Price"]) # da stringa a numero

In [319]:
df["Income"] = df["Price"] * df["Installs"] #creare una nuova colonna per il reddito approssimativo

In [320]:
df[['App','Income']]

                                                     App  Income
2989                              GollerCepte Live Score    0.00
4970                        Ad Block REMOVER - NEED ROOT    0.00
2705                                 SnipSnap Coupon App    0.00
3049                   US Open Tennis Championships 2018    0.00
3229                                          DreamTrips    0.00
7002    Adult Color by Number Book - Paint Mandala Pages    0.00
6724                      BSPlayer ARMv7 VFP CPU support    0.00
7982   Easy Resume Builder, Resume help, Curriculum v...    0.00
353                                    MegaFon Dashboard    0.00
326    Buff Thun - Daily Free Webtoon / Comics / Web ...    0.00
5326                                       Al jazeera TV    0.00
3874                        Rope Hero Return of a Legend    0.00
10383                     Family Guy The Quest for Stuff    0.00
7351                         tutti.ch - Free Classifieds    0.00
2349                                    Teach Me Anatomy    0.00
996                                           Funny Pics    0.00
78                                   Best Car Wallpapers    0.00
9112                                Files To SD Card Pro    0.00
4183                          HSPA+ Tweaker (3G booster)    0.00
6996                Art Pixel Coloring. Color by Number.    0.00
4957                                        Adblock Fast    0.00
1982                                     Zombie Catchers    0.00
741                               Udemy - Online Courses    0.00
3057                      Tennis 24 - tennis live scores    0.00
1021     PTI Flex Maker, Photo Frame Editor & Songs 2018    0.00
3595                                    Kids Craft Ideas    0.00
7826                                   CS Interview FAQs    0.00
8936                                            AKASO DV    0.00
4840                               Z-Empire: Dead Strike    0.00
7443                            Gang Wars of San Andreas    0.00
...                                                  ...     ...
6653                               Bar BQ Tonight Dublin    0.00
478                                    Truth or Dare Pro   74.50
2433                                          RT 516 VET    0.00
9421                                          Verdant EI    0.00
2434                                EXOGEN Connects (US)    0.00
10417                                          FH Wallet    0.00
8828                                        DS Companion    0.00
2435           Full Code - Emergency Medicine Simulation    0.00
2436                                         Maricopa AH    0.00
9414                                            Yeled EI    0.00
479      Private Dating, Hide App- Blue for PrivacyHider  299.00
8871                              Test Application DT 02    0.00
7386                                      RGN CI-Control    0.00
8870                                              PAY DT    0.00
7202                                     ABAI CE Scanner    0.00
5231                                        AJ Reminders    0.00
4273                                J. Polep Plus Mobile    0.00
5688                             Au Rubis les bijoutiers    0.00
6176                                             Dete.bg    0.00
5494                                   AQ: First Contact    0.00
6644                       Bill Miller Bar-B-Q Store Ops    0.00
5234                                        Aj. Vallbona    0.00
2422                                           Visualmed    2.99
8851                                                  DT    0.00
7384                      All-night drugstore CI & Price    9.90
5232                           tournaments and more.aj.2    0.00
7382                           1st Fed CI Mobile Banking    0.00
2424                                           OrthoFlow   59.90
10399                     Familial Hypercholesterolaemia    0.00
5113                                    Ag-Pro Companies    0.00

[9657 rows x 2 columns]

In [321]:
print("The app " + str(df['App'].loc[4137]) + " has an income of " + str(df['Income'].loc[4137]))

The app F-1 watchface by Delta has an income of 24.900000000000002

For each app, compute its minimum and maximum Sentiment_polarity

In [322]:
df1.head()

,App,Translated_Review,Sentiment,Sentiment_Polarity,Sentiment_Subjectivity
0,10 Best Foods for You,I like eat delicious food. That's I'm cooking ...,Positive,1.00,0.533333
1,10 Best Foods for You,This help eating healthy exercise regular basis,Positive,0.25,0.288462
2,10 Best Foods for You,NaN,NaN,NaN,NaN
3,10 Best Foods for You,Works great especially going grocery store,Positive,0.40,0.875000
4,10 Best Foods for You,Best idea us,Positive,1.00,0.300000

In [323]:
sentmin = df1.groupby('App')['Sentiment_Polarity'].min()
sentmin

App
10 Best Foods for You                                -0.800000
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室                     -0.112500
11st                                                 -1.000000
1800 Contacts - Lens Store                           -0.300000
1LINE – One Line with One Touch                      -0.825000
2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif     -0.800000
21-Day Meditation Experience                         -0.265625
2Date Dating App, Love and matching                  -0.645833
2GIS: directory & navigator                          -0.375000
2RedBeans                                            -0.800000
2ndLine - Second Phone Number                        -0.781250
30 Day Fitness Challenge - Workout at Home           -0.500000
365Scores - Live Scores                               0.000000
3D Blue Glass Water Keyboard Theme                         NaN
3D Color Pixel by Number - Sandbox Art Coloring            NaN
3D Live Neon Weed Launcher                            0.136364
4 in a Row                                           -0.800000
4K Wallpapers and Ultra HD Backgrounds               -0.700000
591房屋交易-租屋、中古屋、新建案、實價登錄、別墅透天、公寓套房、捷運、買房賣房行情、房價房貸查詢   -0.300000
591房屋交易-香港                                           -0.077083
7 Cups: Anxiety & Stress Chat                        -0.172222
7 Day Food Journal Challenge                          0.070000
7 Minute Workout                                     -0.291667
7 Weeks - Habit & Goal Tracker                       -0.132576
8 Ball Pool                                          -1.000000
850 Sports News Digest                               -0.500000
8fit Workouts & Meal Planner                         -0.700000
95Live -SG#1 Live Streaming App                      -0.937500
A Call From Santa Claus!                             -1.000000
A Manual of Acupuncture                                    NaN
                                                        ...
Hole19: Golf GPS App, Rangefinder & Scorecard         0.000000
Home Decor Showpiece Art making: Medium Difficulty   -1.000000
Home Scouting® MLS Mobile                            -0.800000
Home Security Camera WardenCam - reuse old phones    -0.800000
Home Street – Home Design Game                       -0.750000
Home Workout - No Equipment                          -0.016667
Home Workout for Men - Bodybuilding                   0.000000
Home workouts - fat burning, abs, legs, arms,chest    0.050000
HomeAway Vacation Rentals                                  NaN
HomeWork                                              1.000000
Homes.com 🏠 For Sale, Rent                           -0.600000
Homescapes                                           -0.197917
Homesnap Real Estate & Rentals                       -0.600000
Homestyler Interior Design & Decorating Ideas        -0.400000
Homework Planner                                     -0.208333
Honkai Impact 3rd                                    -0.237500
Hopper - Watch & Book Flights                        -0.937500
Horoscopes – Daily Zodiac Horoscope and Astrology    -0.040476
Horses Live Wallpaper                                -0.656250
Hostelworld: Hostels & Cheap Hotels Travel App       -1.000000
Hot Wheels: Race Off                                 -0.625000
Hot or Not - Find someone right now                        NaN
HotelTonight: Book amazing deals at great hotels     -1.000000
Hotels Combined - Cheap deals                        -0.700000
Hotels.com: Book Hotel Rooms & Find Vacation Deals   -0.988281
Hotspot Shield Free VPN Proxy & Wi-Fi Security       -0.700000
Hotstar                                              -0.555556
Hotwire Hotel & Car Rental App                       -0.875000
Housing-Real Estate & Property                       -0.528571
Houzz Interior Design Ideas                                NaN
Name: Sentiment_Polarity, Length: 1074, dtype: float64

In [324]:
sentmax = df1.groupby('App')['Sentiment_Polarity'].max()
sentmax

App
10 Best Foods for You                                 1.000000
104 找工作 - 找工作 找打工 找兼職 履歷健檢 履歷診療室                      0.910000
11st                                                  1.000000
1800 Contacts - Lens Store                            0.838542
1LINE – One Line with One Touch                       1.000000
2018Emoji Keyboard 😂 Emoticons Lite -sticker&gif      1.000000
21-Day Meditation Experience                          0.587500
2Date Dating App, Love and matching                   1.000000
2GIS: directory & navigator                           1.000000
2RedBeans                                             1.000000
2ndLine - Second Phone Number                         1.000000
30 Day Fitness Challenge - Workout at Home            0.900000
365Scores - Live Scores                               1.000000
3D Blue Glass Water Keyboard Theme                         NaN
3D Color Pixel by Number - Sandbox Art Coloring            NaN
3D Live Neon Weed Launcher                            1.000000
4 in a Row                                            1.000000
4K Wallpapers and Ultra HD Backgrounds                0.750000
591房屋交易-租屋、中古屋、新建案、實價登錄、別墅透天、公寓套房、捷運、買房賣房行情、房價房貸查詢    0.700000
591房屋交易-香港                                            0.700000
7 Cups: Anxiety & Stress Chat                         0.812500
7 Day Food Journal Challenge                          0.343333
7 Minute Workout                                      1.000000
7 Weeks - Habit & Goal Tracker                        0.471212
8 Ball Pool                                           0.650000
850 Sports News Digest                                1.000000
8fit Workouts & Meal Planner                          0.800000
95Live -SG#1 Live Streaming App                       1.000000
A Call From Santa Claus!                              0.700000
A Manual of Acupuncture                                    NaN
                                                        ...
Hole19: Golf GPS App, Rangefinder & Scorecard         1.000000
Home Decor Showpiece Art making: Medium Difficulty    0.780000
Home Scouting® MLS Mobile                             1.000000
Home Security Camera WardenCam - reuse old phones     1.000000
Home Street – Home Design Game                        0.600000
Home Workout - No Equipment                           1.000000
Home Workout for Men - Bodybuilding                   1.000000
Home workouts - fat burning, abs, legs, arms,chest    0.800000
HomeAway Vacation Rentals                                  NaN
HomeWork                                              1.000000
Homes.com 🏠 For Sale, Rent                            1.000000
Homescapes                                            0.503571
Homesnap Real Estate & Rentals                        1.000000
Homestyler Interior Design & Decorating Ideas         0.988281
Homework Planner                                      0.718750
Honkai Impact 3rd                                     0.775000
Hopper - Watch & Book Flights                         0.761905
Horoscopes – Daily Zodiac Horoscope and Astrology     1.000000
Horses Live Wallpaper                                 1.000000
Hostelworld: Hostels & Cheap Hotels Travel App        1.000000
Hot Wheels: Race Off                                  0.391667
Hot or Not - Find someone right now                        NaN
HotelTonight: Book amazing deals at great hotels      1.000000
Hotels Combined - Cheap deals                         1.000000
Hotels.com: Book Hotel Rooms & Find Vacation Deals    0.700000
Hotspot Shield Free VPN Proxy & Wi-Fi Security        1.000000
Hotstar                                               1.000000
Hotwire Hotel & Car Rental App                        0.800000
Housing-Real Estate & Property                        0.800000
Houzz Interior Design Ideas                                NaN
Name: Sentiment_Polarity, Length: 1074, dtype: float64

In [325]:
print("The app |" + str(df1.groupby('App')['Sentiment_Polarity'].min().index[0]) + "| has a minimum value of " + str(df1.groupby('App')['Sentiment_Polarity'].min().iloc[0]) + " and a maximum value of " + str(df1.groupby('App')['Sentiment_Polarity'].max().iloc[0]))

The app |10 Best Foods for You| has a minimum value of -0.8 and a maximum value of 1.0